# Generated by Django 4.2.1 on 2023-05-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDate',
        ),
    ]
